### ISSUE TITLE
how to set pin mode

### ISSUE THREAD

**Issue by djsg** [xreef/PCF8575_library#10]
Hi,

From datasheet, I only figured out if I want to set a pin (e.g P17) to output LOW, I can use I2C to write 3 bytes as the following:
0100 A2A1A00
0xxx xxxx
xxxx xxxx

Is it correct? But I cannot figure out how to set P17 to output mode.

**Comment by xreef** [comment]
Sorry If I lost this message... I add a workaround to this problem with [this define](https://github.com/xreef/PCF8575_library/blob/master/PCF8575.h#L50) to get the original pins, not the sequential ones.
Bye Renzo
