### ISSUE TITLE
Request: initial pin state on begin

### ISSUE THREAD

**Issue by codewise-nicolas** [xreef/PCF8575_library#3]
Any chance you can do the same fix you did here https://github.com/xreef/PCF8574_library/issues/15 to the PCF8575 library ?
This would allow setting the pin state on .begin(). 

Currently I hacked the .cpp file on line 179 as follows:
`uint16_t usedPin = readMode; //writeMode |`
And this works (as per datasheet 0 on a write call sets the pin low) but have not fully tested it.

**Comment by xreef** [comment]
Hi codewise-nicolas,
sorry I lost this issue, now I don't do that change, the develop of pcf8574 isn't so simple, 
but If I fond some time I update also this library with the same features.
Bye Renzo
