### ISSUE TITLE
When I must use BEGIN

### ISSUE THREAD

**Issue by pruwait** [xreef/PCF8575_library#7]
I have ESP32 and 2 PCF8575 like inputs + 2 PCF8575 like outputs on standart 21-22 SDA SSL.

`//Все GPIO могут быть настроены для обработки прерываний.
#define ESP32_INTERRUPTED_PIN1 2
#define ESP32_INTERRUPTED_PIN2 3

//адреса расширителей
#define addrIn1 0x20
#define addrIn2 0x21
#define addrOut1 0x22
#define addrOut2 0x23

// Function interrupt
void keyChangedOnPCF1();
void keyChangedOnPCF2();

bool keyChanged1 = false;
bool keyChanged2 = false;

PCF8575 in1(addrIn1, ESP32_INTERRUPTED_PIN1,  keyChangedOnPCF1);
PCF8575 in2(addrIn2, ESP32_INTERRUPTED_PIN2,  keyChangedOnPCF2);
PCF8575 out1(addrOut1);
PCF8575 out2(addrOut2);

//uint32_t click_st, dbl_st, hold_st;  // переменные для текуших статусов входных сигналов

struct Button {
  const uint8_t PIN;
  bool pressed;
  bool dbl;
  bool hold;
};

unsigned long timeElapsed;

byte mac[] = {
  0x00, 0xAA, 0xBB, 0xCC, 0xDE, 0x02
};

void setup() {
  Serial.begin(112560);

  // Set pinMode to OUTPUT
  for (uint8_t i = 0; i < 16; i++) {
    in1.pinMode(i, INPUT);
    in2.pinMode(i, INPUT);
    out1.pinMode(i, INPUT);
    out2.pinMode(i, INPUT);
  }
  //in1.begin(); //
  //in2.begin();
  //out1.begin();
  //out2.begin();`

I need using *.begin 4 times or no need begin for esp32 and 21-22 SDA-SCL?

**Comment by xreef** [comment]
Hi pruwait,
yes you need 4 begin of pcf8575 and no other. Internally the library call begin of Wire.
Bye Renzo
