### ISSUE TITLE
create array of PCF8575

### ISSUE THREAD

**Issue by ear9mrn** [xreef/PCF8575_library#8]
I would to declare an array of multiple PCF8575 devices within a struct, something like:

`PCF8575   PCF[DEVICES];`

Then, in another part of my code do something like:

`PCF[0].digitalRead(PINNUM);`

I cannot figure out how to do this with this library as it appears at minimum I need to assign an address with the constructor.

Any suggestions would be greatly appreciated.

Thanks.

**Comment by xreef** [comment]
Ops, sorry I lost this message.

You can find some examples here
https://www.mischianti.org/forums/topic/more-than-one-pcf8574-expander/

Bye Renzo
